/** GenoMetric Space Explorer (GeMSE) Copyright (C) 2017 Vahid Jalili
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 3 of the License, or
 *  (at your option) any later version.
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, write to the Free Software Foundation,
 *  Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301  USA
 */
package GeMSE.GS.Transitions.Panels;

import GeMSE.GS.Transitions.Options.DiscretizeOptions;
import GeMSE.GS.Transitions.Options.Map;
import java.math.RoundingMode;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.util.ArrayList;
import javax.swing.ButtonGroup;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Vahid Jalili
 */
public class RewriteOptionsPanel extends javax.swing.JPanel
{
    public RewriteOptionsPanel()
    {
        initComponents();
        _maps = new ArrayList<>();

        NewValue_TB.setEnabled(true);
        logBaseS.setEnabled(false);
        ButtonGroup groupA = new ButtonGroup();
        groupA.add(staticNewValueRB);
        groupA.add(logTransformationRB);
        staticNewValueRB.setSelected(true);

        _decFor = new DecimalFormat("#.#");
        _decFor.setRoundingMode(RoundingMode.CEILING);
        DecimalFormatSymbols decFors = _decFor.getDecimalFormatSymbols();
        decFors.setNaN("NaN");
        decFors.setInfinity("∞");
        _decFor.setDecimalFormatSymbols(decFors);
    }

    private DecimalFormat _decFor;
    private ArrayList<Map> _maps;
    private double _minValue;
    private double _maxValue;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        Rows_Range_L = new javax.swing.JLabel();
        RowsFrom_TB = new javax.swing.JTextField();
        RowsTo_TB = new javax.swing.JTextField();
        Columns_Range_L = new javax.swing.JLabel();
        ColumnsFrom_TB = new javax.swing.JTextField();
        ColumnsTo_TB = new javax.swing.JTextField();
        From_L = new javax.swing.JLabel();
        To_L = new javax.swing.JLabel();
        Operation_Range_L1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Defined_Mappings = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        staticNewValueRB = new javax.swing.JRadioButton();
        NewValue_TB = new javax.swing.JTextField();
        logTransformationRB = new javax.swing.JRadioButton();
        logBaseS = new javax.swing.JSpinner();
        New_Value_L = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        Mapping_L = new javax.swing.JLabel();
        Mapping_From_L = new javax.swing.JLabel();
        Mapping_To_L = new javax.swing.JLabel();
        Source_Range_L = new javax.swing.JLabel();
        MappingFrom_TB = new javax.swing.JTextField();
        MappingTo_TB = new javax.swing.JTextField();
        minMaxValueL = new javax.swing.JLabel();
        minValue = new javax.swing.JLabel();
        maxValue = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        Reset_BT = new javax.swing.JButton();
        Add_Mapping_BT = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(258, 32767));
        setMinimumSize(new java.awt.Dimension(258, 510));
        setPreferredSize(new java.awt.Dimension(258, 520));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(10, 500));

        Rows_Range_L.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Rows_Range_L.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Rows_Range_L.setText("Rows");
        Rows_Range_L.setMaximumSize(new java.awt.Dimension(60, 20));
        Rows_Range_L.setMinimumSize(new java.awt.Dimension(60, 20));
        Rows_Range_L.setPreferredSize(new java.awt.Dimension(60, 20));

        RowsFrom_TB.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        RowsFrom_TB.setText("0");

        RowsTo_TB.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        RowsTo_TB.setText("100");

        Columns_Range_L.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Columns_Range_L.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Columns_Range_L.setText("Columns");
        Columns_Range_L.setMaximumSize(new java.awt.Dimension(60, 20));
        Columns_Range_L.setMinimumSize(new java.awt.Dimension(60, 20));
        Columns_Range_L.setPreferredSize(new java.awt.Dimension(60, 20));

        ColumnsFrom_TB.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ColumnsFrom_TB.setText("0");

        ColumnsTo_TB.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ColumnsTo_TB.setText("100");

        From_L.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        From_L.setText("From");
        From_L.setMaximumSize(new java.awt.Dimension(60, 20));
        From_L.setMinimumSize(new java.awt.Dimension(60, 20));
        From_L.setPreferredSize(new java.awt.Dimension(60, 20));

        To_L.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        To_L.setText("To");
        To_L.setMaximumSize(new java.awt.Dimension(60, 20));
        To_L.setMinimumSize(new java.awt.Dimension(60, 20));
        To_L.setPreferredSize(new java.awt.Dimension(60, 20));

        Operation_Range_L1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Operation_Range_L1.setText("Operation Application Range");
        Operation_Range_L1.setMaximumSize(new java.awt.Dimension(60, 20));
        Operation_Range_L1.setMinimumSize(new java.awt.Dimension(60, 20));
        Operation_Range_L1.setPreferredSize(new java.awt.Dimension(60, 20));

        Defined_Mappings.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {
                "From", "To", "New"
            }
        )
        {
            Class[] types = new Class []
            {
                java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean []
            {
                false, false, false
            };

            public Class getColumnClass(int columnIndex)
            {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Defined_Mappings);

        staticNewValueRB.setText("Constant");
        staticNewValueRB.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                staticNewValueRBActionPerformed(evt);
            }
        });

        NewValue_TB.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NewValue_TB.setText("0");

        logTransformationRB.setText("Log trans. base: ");
        logTransformationRB.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                logTransformationRBActionPerformed(evt);
            }
        });

        logBaseS.setModel(new javax.swing.SpinnerNumberModel(2, 2, 20, 1));

        New_Value_L.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        New_Value_L.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        New_Value_L.setText("New Value");
        New_Value_L.setMaximumSize(new java.awt.Dimension(60, 20));
        New_Value_L.setMinimumSize(new java.awt.Dimension(60, 20));
        New_Value_L.setPreferredSize(new java.awt.Dimension(60, 20));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(staticNewValueRB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NewValue_TB, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(logTransformationRB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(logBaseS, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(New_Value_L, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(New_Value_L, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(staticNewValueRB)
                    .addComponent(NewValue_TB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logTransformationRB)
                    .addComponent(logBaseS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1))
        );

        Mapping_L.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Mapping_L.setText("Mapping ");
        Mapping_L.setMaximumSize(new java.awt.Dimension(60, 20));
        Mapping_L.setMinimumSize(new java.awt.Dimension(60, 20));
        Mapping_L.setPreferredSize(new java.awt.Dimension(60, 20));

        Mapping_From_L.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Mapping_From_L.setText("From");
        Mapping_From_L.setMaximumSize(new java.awt.Dimension(60, 20));
        Mapping_From_L.setMinimumSize(new java.awt.Dimension(60, 20));
        Mapping_From_L.setPreferredSize(new java.awt.Dimension(60, 20));

        Mapping_To_L.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Mapping_To_L.setText("To");
        Mapping_To_L.setMaximumSize(new java.awt.Dimension(60, 20));
        Mapping_To_L.setMinimumSize(new java.awt.Dimension(60, 20));
        Mapping_To_L.setPreferredSize(new java.awt.Dimension(60, 20));

        Source_Range_L.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Source_Range_L.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Source_Range_L.setText("Source Range");
        Source_Range_L.setMaximumSize(new java.awt.Dimension(60, 20));
        Source_Range_L.setMinimumSize(new java.awt.Dimension(60, 20));
        Source_Range_L.setPreferredSize(new java.awt.Dimension(60, 20));

        MappingFrom_TB.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        MappingFrom_TB.setText("0");

        MappingTo_TB.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        MappingTo_TB.setText("100");

        minMaxValueL.setFont(new java.awt.Font("Lucida Grande", 2, 11)); // NOI18N
        minMaxValueL.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        minMaxValueL.setText("min/max");

        minValue.setFont(new java.awt.Font("Lucida Grande", 2, 11)); // NOI18N
        minValue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minValue.setText("NaN");

        maxValue.setFont(new java.awt.Font("Lucida Grande", 2, 11)); // NOI18N
        maxValue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        maxValue.setText("NaN");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Mapping_L, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(Source_Range_L, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(Mapping_From_L, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Mapping_To_L, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(MappingFrom_TB, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(MappingTo_TB, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(minMaxValueL, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(minValue, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(maxValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(Mapping_L, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Mapping_From_L, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Mapping_To_L, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Source_Range_L, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MappingFrom_TB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MappingTo_TB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(minMaxValueL)
                    .addComponent(minValue)
                    .addComponent(maxValue)))
        );

        Reset_BT.setText("Reset");
        Reset_BT.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                Reset_BTActionPerformed(evt);
            }
        });

        Add_Mapping_BT.setText("Add");
        Add_Mapping_BT.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                Add_Mapping_BTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Reset_BT, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Add_Mapping_BT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Reset_BT)
                    .addComponent(Add_Mapping_BT))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(Operation_Range_L1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Columns_Range_L, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(ColumnsFrom_TB, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ColumnsTo_TB, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Rows_Range_L, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(RowsFrom_TB)
                                    .addComponent(From_L, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(To_L, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(RowsTo_TB))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Operation_Range_L1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(From_L, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(To_L, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(RowsTo_TB)
                    .addComponent(RowsFrom_TB)
                    .addComponent(Rows_Range_L, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ColumnsTo_TB)
                    .addComponent(Columns_Range_L, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ColumnsFrom_TB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void Add_Mapping_BTActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_Add_Mapping_BTActionPerformed
    {//GEN-HEADEREND:event_Add_Mapping_BTActionPerformed
        if (staticNewValueRB.isSelected())
        {
            _maps.add(new Map(
                    Double.valueOf(MappingFrom_TB.getText()),
                    Double.valueOf(MappingTo_TB.getText()),
                    Map.Function.Static,
                    Double.valueOf(NewValue_TB.getText())));
        }
        else
        {
            _maps.add(new Map(
                    Double.valueOf(MappingFrom_TB.getText()),
                    Double.valueOf(MappingTo_TB.getText()),
                    Map.Function.Log,
                    (double) ((Integer) logBaseS.getValue())));
        }

        UpdateDefinedMapsDG();
    }//GEN-LAST:event_Add_Mapping_BTActionPerformed

    private void Reset_BTActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_Reset_BTActionPerformed
    {//GEN-HEADEREND:event_Reset_BTActionPerformed
        _maps.clear();
        UpdateDefinedMapsDG();
    }//GEN-LAST:event_Reset_BTActionPerformed

    private void staticNewValueRBActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_staticNewValueRBActionPerformed
    {//GEN-HEADEREND:event_staticNewValueRBActionPerformed
        NewValue_TB.setEnabled(true);
        logBaseS.setEnabled(false);
    }//GEN-LAST:event_staticNewValueRBActionPerformed

    private void logTransformationRBActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_logTransformationRBActionPerformed
    {//GEN-HEADEREND:event_logTransformationRBActionPerformed
        NewValue_TB.setEnabled(false);
        logBaseS.setEnabled(true);
    }//GEN-LAST:event_logTransformationRBActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add_Mapping_BT;
    private javax.swing.JTextField ColumnsFrom_TB;
    private javax.swing.JTextField ColumnsTo_TB;
    private javax.swing.JLabel Columns_Range_L;
    private javax.swing.JTable Defined_Mappings;
    private javax.swing.JLabel From_L;
    private javax.swing.JTextField MappingFrom_TB;
    private javax.swing.JTextField MappingTo_TB;
    private javax.swing.JLabel Mapping_From_L;
    private javax.swing.JLabel Mapping_L;
    private javax.swing.JLabel Mapping_To_L;
    private javax.swing.JTextField NewValue_TB;
    private javax.swing.JLabel New_Value_L;
    private javax.swing.JLabel Operation_Range_L1;
    private javax.swing.JButton Reset_BT;
    private javax.swing.JTextField RowsFrom_TB;
    private javax.swing.JTextField RowsTo_TB;
    private javax.swing.JLabel Rows_Range_L;
    private javax.swing.JLabel Source_Range_L;
    private javax.swing.JLabel To_L;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner logBaseS;
    private javax.swing.JRadioButton logTransformationRB;
    private javax.swing.JLabel maxValue;
    private javax.swing.JLabel minMaxValueL;
    private javax.swing.JLabel minValue;
    private javax.swing.JRadioButton staticNewValueRB;
    // End of variables declaration//GEN-END:variables

    public DiscretizeOptions GetValues()
    {
        DiscretizeOptions options
                          = new DiscretizeOptions(
                        _minValue,
                        _maxValue,
                        Integer.valueOf(ColumnsFrom_TB.getText()),
                        Integer.valueOf(ColumnsTo_TB.getText()),
                        Integer.valueOf(RowsFrom_TB.getText()),
                        Integer.valueOf(RowsTo_TB.getText()));
        options.maps = _maps;
        return options;
    }

    public void SetValues(DiscretizeOptions values)
    {
        if (values != null)
        {
            ColumnsFrom_TB.setText(String.valueOf(values.range.ColumnFrom));
            ColumnsTo_TB.setText(String.valueOf(values.range.ColumnTo));
            RowsFrom_TB.setText(String.valueOf(values.range.RowFrom));
            RowsTo_TB.setText(String.valueOf(values.range.RowTo));

            minValue.setText(String.valueOf(_decFor.format(values.GetMinValue())));
            maxValue.setText(String.valueOf(_decFor.format(values.GetMaxValue())));

            _maps = new ArrayList<>();
            if (values.maps != null)
                for (Map map : values.maps)
                    _maps.add(new Map(
                            map.GetRangeStart(),
                            map.GetRaneStop(),
                            map.GetFunction(),
                            map.GetArgument()));
            _minValue = values.GetMinValue();
            _maxValue = values.GetMaxValue();
            UpdateDefinedMapsDG();
        }
        else
        {
            _maps.clear();
            ColumnsFrom_TB.setText("0");
            ColumnsTo_TB.setText("0");
            RowsFrom_TB.setText("0");
            RowsTo_TB.setText("0");
        }

        MappingFrom_TB.setText("0");
        MappingTo_TB.setText("0");
        NewValue_TB.setText("0");
    }


    private void UpdateDefinedMapsDG()
    {
        DefaultTableModel model = new DefaultTableModel()
        {
            @Override
            public boolean isCellEditable(int row, int column)
            {
                return false;
            }
        };

        model.setColumnIdentifiers(new String[]
        {
            "From", "To", "New"
        });

        for (int i = 0 ; i < _maps.size() ; i++)
        {
            if (_maps.get(i).GetFunction() == Map.Function.Static)
            {
                model.addRow(new String[]
                {
                    String.valueOf(_maps.get(i).GetRangeStart()),
                    String.valueOf(_maps.get(i).GetRaneStop()),
                    String.valueOf(_maps.get(i).GetArgument())
                });
            }
            else
            {
                model.addRow(new String[]
                {
                    String.valueOf(_maps.get(i).GetRangeStart()),
                    String.valueOf(_maps.get(i).GetRaneStop()),
                    "Log_" + String.valueOf(_maps.get(i).GetArgument())
                });
            }
        }

        this.Defined_Mappings.setModel(model);
    }
}
