/** GenoMetric Space Explorer (GeMSE) Copyright (C) 2017 Vahid Jalili
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 3 of the License, or
 *  (at your option) any later version.
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, write to the Free Software Foundation,
 *  Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301  USA
 */

package GeMSE.Heatmap;

import GeMSE.GlobalVariables;
import java.awt.Dimension;
import javax.swing.BorderFactory;
import javax.swing.ButtonGroup;

/**
 *
 * @author Vahid Jalili
 */
public class HeatmapOptions extends javax.swing.JFrame
{
    /**
     * Creates new form HeatMapOptions
     */
    public HeatmapOptions()
    {
        initComponents();
        ButtonGroup group = new ButtonGroup();


        InitializeLabelOptions();

        RHeatmapBasicAdvanceOption.add(UseRHeatmapBasic_RB);
        RHeatmapBasicAdvanceOption.add(UseRHeatmapAdvance_RB);

        HeatmapPackageOption_BG.add(UseIPlot_R1);
        HeatmapPackageOption_BG.add(UseRPlot_R);

        RHeatmapSizeOptions_BG.add(ManualSize_RB);
        RHeatmapSizeOptions_BG.add(AutomaticSize_RB);
        if (GlobalVariables.HeatmapOptions.autoFitRPlotSize == true)
        {
            AutomaticSize_RB.setSelected(true);
            AutomaticSize_RB.doClick();
        }
        else
        {
            ManualSize_RB.setSelected(true);
            ManualSize_RB.doClick();
        }

        HeatmapTitle_TB.setText(GlobalVariables.HeatmapOptions.heatmapTitle);
        HorizontalAxisTitle_TB.setText(GlobalVariables.HeatmapOptions.horizontalAxisTitle);
        VerticalAxisTitle_TB.setText(GlobalVariables.HeatmapOptions.verticalAxisTitle);

        RScriptPath_TB.setText(GlobalVariables.HeatmapOptions.RScriptPath);

        if (GlobalVariables.HeatmapOptions.heatmpaType == false)
        {
            UseIPlot_R1.setSelected(true);
            UseIPlot_R1.doClick();
        }
        else
        {
            UseRPlot_R.setSelected(true);
            UseRPlot_R.doClick();
        }

        if (GlobalVariables.HeatmapOptions.autoFitRPlotSize == false
            && GlobalVariables.HeatmapOptions.size != null)
        {
            PlotSizeWidth_TB.setText(String.valueOf(GlobalVariables.HeatmapOptions.size.width));
            PlotSizeHeight_TB.setText(String.valueOf(GlobalVariables.HeatmapOptions.size.height));
        }

        EpsilonDescription.setBorder(BorderFactory.createEmptyBorder());
        EpsilonDescription.setOpaque(false);
        EpsilonDistance_TB.setText(String.valueOf(GlobalVariables.HeatmapOptions.epsilonDistance));
    }

    private void InitializeLabelOptions()
    {
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        RHeatmapBasicAdvanceOption = new javax.swing.ButtonGroup();
        HeatmapPackageOption_BG = new javax.swing.ButtonGroup();
        RHeatmapSizeOptions_BG = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        OK_BT = new javax.swing.JButton();
        Cancel_BT = new javax.swing.JButton();
        HeatmapOption_TP = new javax.swing.JTabbedPane();
        RHeatmap_P = new javax.swing.JPanel();
        RHeatmapOptions_T = new javax.swing.JTabbedPane();
        RHeatmapOptionBasic_P = new javax.swing.JPanel();
        UseRHeatmapBasic_RB = new javax.swing.JRadioButton();
        RHeatmapBasicOptions_SP = new javax.swing.JScrollPane();
        RHeatmapBasicOptions_P = new javax.swing.JPanel();
        RHeatmapLabelingOptions_P = new javax.swing.JPanel();
        RowColLabeling_L = new javax.swing.JLabel();
        RCLMargin_L1 = new javax.swing.JLabel();
        RCLMarginColNames_TB = new javax.swing.JTextField();
        RCLMargin_L2 = new javax.swing.JLabel();
        RCLMarginRowNames_TB = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        Titles_L1 = new javax.swing.JLabel();
        HeatmapTitle_L = new javax.swing.JLabel();
        HorizontalAxisTitle_L = new javax.swing.JLabel();
        VerticalAxisTitle_L = new javax.swing.JLabel();
        HeatmapTitle_TB = new javax.swing.JTextField();
        HorizontalAxisTitle_TB = new javax.swing.JTextField();
        VerticalAxisTitle_TB = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        AutomaticSize_RB = new javax.swing.JRadioButton();
        PlotSize_L = new javax.swing.JLabel();
        ManualSize_RB = new javax.swing.JRadioButton();
        PlotSizeHeight_L = new javax.swing.JLabel();
        PlotSizeHeight_TB = new javax.swing.JTextField();
        PlotSizeWidth_L = new javax.swing.JLabel();
        PlotSizeWidth_TB = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        EpsilonDistance_TB = new javax.swing.JTextField();
        EpsilonDistance_L = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        EpsilonDescription = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        RHeatmapOptionAdvance_P = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        RHeatmapAdvancedOptions = new javax.swing.JEditorPane();
        UseRHeatmapAdvance_RB = new javax.swing.JRadioButton();
        UseRPlot_R = new javax.swing.JRadioButton();
        RScriptPath_TB = new javax.swing.JTextField();
        RScriptPathLabel = new javax.swing.JLabel();
        UseIPlot_R1 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        OK_BT.setText("OK");
        OK_BT.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                OK_BTActionPerformed(evt);
            }
        });

        Cancel_BT.setText("Cancel");
        Cancel_BT.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                Cancel_BTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(OK_BT, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Cancel_BT, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cancel_BT)
                    .addComponent(OK_BT))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        HeatmapOption_TP.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        RHeatmap_P.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        UseRHeatmapBasic_RB.setText("Use basic settings as following");
        UseRHeatmapBasic_RB.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                UseRHeatmapBasic_RBActionPerformed(evt);
            }
        });

        RowColLabeling_L.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        RowColLabeling_L.setText("Row/Column Labeling");

        RCLMargin_L1.setText("Margins :   Column names ");

        RCLMarginColNames_TB.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        RCLMarginColNames_TB.setText("0");

        RCLMargin_L2.setText("Row names ");

        RCLMarginRowNames_TB.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        RCLMarginRowNames_TB.setText("0");

        javax.swing.GroupLayout RHeatmapLabelingOptions_PLayout = new javax.swing.GroupLayout(RHeatmapLabelingOptions_P);
        RHeatmapLabelingOptions_P.setLayout(RHeatmapLabelingOptions_PLayout);
        RHeatmapLabelingOptions_PLayout.setHorizontalGroup(
            RHeatmapLabelingOptions_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RHeatmapLabelingOptions_PLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(RHeatmapLabelingOptions_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RowColLabeling_L)
                    .addGroup(RHeatmapLabelingOptions_PLayout.createSequentialGroup()
                        .addComponent(RCLMargin_L1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RCLMarginColNames_TB, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(RCLMargin_L2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RCLMarginRowNames_TB, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        RHeatmapLabelingOptions_PLayout.setVerticalGroup(
            RHeatmapLabelingOptions_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RHeatmapLabelingOptions_PLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RowColLabeling_L)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(RHeatmapLabelingOptions_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RCLMargin_L1)
                    .addComponent(RCLMarginColNames_TB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RCLMargin_L2)
                    .addComponent(RCLMarginRowNames_TB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Titles_L1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Titles_L1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titles_L1.setText("Titles");

        HeatmapTitle_L.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        HeatmapTitle_L.setText("Heatmap Title");

        HorizontalAxisTitle_L.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        HorizontalAxisTitle_L.setText("Horizontal Axis Title");

        VerticalAxisTitle_L.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        VerticalAxisTitle_L.setText("Vertical Axis Title");

        HeatmapTitle_TB.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        HorizontalAxisTitle_TB.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        VerticalAxisTitle_TB.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Titles_L1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(VerticalAxisTitle_L, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(HorizontalAxisTitle_L, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(HeatmapTitle_L, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(VerticalAxisTitle_TB)
                    .addComponent(HorizontalAxisTitle_TB, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(HeatmapTitle_TB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE))
                .addGap(13, 13, 13))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(Titles_L1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(HeatmapTitle_L)
                            .addComponent(HeatmapTitle_TB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(HorizontalAxisTitle_L)
                            .addComponent(HorizontalAxisTitle_TB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(VerticalAxisTitle_L)
                            .addComponent(VerticalAxisTitle_TB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 1, Short.MAX_VALUE)))
                .addGap(14, 14, 14))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        AutomaticSize_RB.setSelected(true);
        AutomaticSize_RB.setText("Automatic, Fit to window size");
        AutomaticSize_RB.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                AutomaticSize_RBActionPerformed(evt);
            }
        });

        PlotSize_L.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        PlotSize_L.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PlotSize_L.setText("Size");

        ManualSize_RB.setText("Manual window size");
        ManualSize_RB.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                ManualSize_RBActionPerformed(evt);
            }
        });

        PlotSizeHeight_L.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PlotSizeHeight_L.setText("Height");
        PlotSizeHeight_L.setEnabled(false);

        PlotSizeHeight_TB.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PlotSizeHeight_TB.setText("1");
        PlotSizeHeight_TB.setEnabled(false);

        PlotSizeWidth_L.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PlotSizeWidth_L.setText("Width");
        PlotSizeWidth_L.setEnabled(false);

        PlotSizeWidth_TB.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PlotSizeWidth_TB.setText("1");
        PlotSizeWidth_TB.setEnabled(false);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PlotSize_L, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(ManualSize_RB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(PlotSizeHeight_TB, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(PlotSizeWidth_TB, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(PlotSizeHeight_L, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(PlotSizeWidth_L, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(AutomaticSize_RB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PlotSizeHeight_L)
                            .addComponent(PlotSizeWidth_L))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PlotSizeHeight_TB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PlotSizeWidth_TB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ManualSize_RB))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(AutomaticSize_RB)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(PlotSize_L, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(14, 14, 14))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        EpsilonDistance_TB.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        EpsilonDistance_TB.setText("1E-4");

        EpsilonDistance_L.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        EpsilonDistance_L.setText("value");

        EpsilonDescription.setEditable(false);
        EpsilonDescription.setColumns(20);
        EpsilonDescription.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        EpsilonDescription.setLineWrap(true);
        EpsilonDescription.setRows(5);
        EpsilonDescription.setText("Is a neglectable value added to the estimated distance between two vectors to avoid multiple vectors with zero distance from each other which raises issues with gplots.");
        EpsilonDescription.setWrapStyleWord(true);
        EpsilonDescription.setAutoscrolls(false);
        EpsilonDescription.setBorder(null);
        EpsilonDescription.setOpaque(false);
        jScrollPane1.setViewportView(EpsilonDescription);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Epsilon distance");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(EpsilonDistance_L)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(EpsilonDistance_TB, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(EpsilonDistance_TB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(EpsilonDistance_L))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(9, 9, 9)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout RHeatmapBasicOptions_PLayout = new javax.swing.GroupLayout(RHeatmapBasicOptions_P);
        RHeatmapBasicOptions_P.setLayout(RHeatmapBasicOptions_PLayout);
        RHeatmapBasicOptions_PLayout.setHorizontalGroup(
            RHeatmapBasicOptions_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RHeatmapBasicOptions_PLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(RHeatmapBasicOptions_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RHeatmapLabelingOptions_P, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        RHeatmapBasicOptions_PLayout.setVerticalGroup(
            RHeatmapBasicOptions_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RHeatmapBasicOptions_PLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RHeatmapLabelingOptions_P, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        RHeatmapBasicOptions_SP.setViewportView(RHeatmapBasicOptions_P);

        javax.swing.GroupLayout RHeatmapOptionBasic_PLayout = new javax.swing.GroupLayout(RHeatmapOptionBasic_P);
        RHeatmapOptionBasic_P.setLayout(RHeatmapOptionBasic_PLayout);
        RHeatmapOptionBasic_PLayout.setHorizontalGroup(
            RHeatmapOptionBasic_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RHeatmapOptionBasic_PLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(RHeatmapOptionBasic_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RHeatmapOptionBasic_PLayout.createSequentialGroup()
                        .addComponent(UseRHeatmapBasic_RB)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(RHeatmapBasicOptions_SP))
                .addContainerGap())
        );
        RHeatmapOptionBasic_PLayout.setVerticalGroup(
            RHeatmapOptionBasic_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RHeatmapOptionBasic_PLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(UseRHeatmapBasic_RB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RHeatmapBasicOptions_SP)
                .addContainerGap())
        );

        RHeatmapOptions_T.addTab("       Basic       ", RHeatmapOptionBasic_P);

        jScrollPane2.setViewportView(RHeatmapAdvancedOptions);

        UseRHeatmapAdvance_RB.setText("Use advanced settings as following");
        UseRHeatmapAdvance_RB.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                UseRHeatmapAdvance_RBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout RHeatmapOptionAdvance_PLayout = new javax.swing.GroupLayout(RHeatmapOptionAdvance_P);
        RHeatmapOptionAdvance_P.setLayout(RHeatmapOptionAdvance_PLayout);
        RHeatmapOptionAdvance_PLayout.setHorizontalGroup(
            RHeatmapOptionAdvance_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 638, Short.MAX_VALUE)
            .addGroup(RHeatmapOptionAdvance_PLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(UseRHeatmapAdvance_RB)
                .addContainerGap(378, Short.MAX_VALUE))
        );
        RHeatmapOptionAdvance_PLayout.setVerticalGroup(
            RHeatmapOptionAdvance_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RHeatmapOptionAdvance_PLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(UseRHeatmapAdvance_RB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 525, Short.MAX_VALUE))
        );

        RHeatmapOptions_T.addTab("   Advanced   ", RHeatmapOptionAdvance_P);

        UseRPlot_R.setText("use R package gplots ( heatmap 2 ) for heatmap");
        UseRPlot_R.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                UseRPlot_RActionPerformed(evt);
            }
        });

        RScriptPath_TB.setText("Vahid");

        RScriptPathLabel.setText("RScript path");

        UseIPlot_R1.setSelected(true);
        UseIPlot_R1.setText("use integrated package for heatmap");
        UseIPlot_R1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                UseIPlot_R1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout RHeatmap_PLayout = new javax.swing.GroupLayout(RHeatmap_P);
        RHeatmap_P.setLayout(RHeatmap_PLayout);
        RHeatmap_PLayout.setHorizontalGroup(
            RHeatmap_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RHeatmap_PLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(RHeatmap_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RHeatmapOptions_T)
                    .addGroup(RHeatmap_PLayout.createSequentialGroup()
                        .addComponent(RScriptPathLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(RScriptPath_TB))
                    .addGroup(RHeatmap_PLayout.createSequentialGroup()
                        .addGroup(RHeatmap_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(UseRPlot_R)
                            .addComponent(UseIPlot_R1))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        RHeatmap_PLayout.setVerticalGroup(
            RHeatmap_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RHeatmap_PLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(UseIPlot_R1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(UseRPlot_R)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RHeatmap_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RScriptPath_TB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RScriptPathLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RHeatmapOptions_T)
                .addContainerGap())
        );

        HeatmapOption_TP.addTab("Heatmap options", RHeatmap_P);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(HeatmapOption_TP, javax.swing.GroupLayout.DEFAULT_SIZE, 719, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(HeatmapOption_TP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Cancel_BTActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_Cancel_BTActionPerformed
    {//GEN-HEADEREND:event_Cancel_BTActionPerformed
        this.dispose();
    }//GEN-LAST:event_Cancel_BTActionPerformed

    private void OK_BTActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_OK_BTActionPerformed
    {//GEN-HEADEREND:event_OK_BTActionPerformed
        if (UseIPlot_R1.isSelected())
        {
            GlobalVariables.HeatmapOptions.heatmpaType = false;
        }
        else
        {
            GlobalVariables.HeatmapOptions.heatmpaType = true;
            GlobalVariables.HeatmapOptions.heatmapCommand = GenerateRHeatmapCommand();
            GlobalVariables.HeatmapOptions.size = new Dimension(Integer.valueOf(PlotSizeWidth_TB.getText()), Integer.valueOf(PlotSizeHeight_TB.getText()));
            GlobalVariables.HeatmapOptions.autoFitRPlotSize = AutomaticSize_RB.isSelected();
        }

        GlobalVariables.HeatmapOptions.heatmapTitle = HeatmapTitle_TB.getText();
        GlobalVariables.HeatmapOptions.horizontalAxisTitle = HorizontalAxisTitle_TB.getText();
        GlobalVariables.HeatmapOptions.verticalAxisTitle = VerticalAxisTitle_TB.getText();
        GlobalVariables.HeatmapOptions.RScriptPath = RScriptPath_TB.getText();
        GlobalVariables.HeatmapOptions.epsilonDistance = Double.valueOf(EpsilonDistance_TB.getText());

        if (UseRHeatmapBasic_RB.isSelected())
            GlobalVariables.HeatmapOptions.RBAOptions = true;
        else
            GlobalVariables.HeatmapOptions.RBAOptions = false;

        this.dispose();
    }//GEN-LAST:event_OK_BTActionPerformed

    private void UseRPlot_RActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_UseRPlot_RActionPerformed
    {//GEN-HEADEREND:event_UseRPlot_RActionPerformed
        EnableDisable_RHeatMapOptions(true);
        if (GlobalVariables.HeatmapOptions.RBAOptions == true)
        {
            UseRHeatmapBasic_RB.setSelected(true);
            UseRHeatmapBasic_RB.doClick();
        }
        else
        {
            UseRHeatmapAdvance_RB.setSelected(true);
            UseRHeatmapAdvance_RB.doClick();
        }
    }//GEN-LAST:event_UseRPlot_RActionPerformed

    private void UseRHeatmapAdvance_RBActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_UseRHeatmapAdvance_RBActionPerformed
    {//GEN-HEADEREND:event_UseRHeatmapAdvance_RBActionPerformed
        EnableDisable_ARHOptions(UseRHeatmapAdvance_RB.isSelected());
        EnableDisable_BRHOptions(!UseRHeatmapAdvance_RB.isSelected());
    }//GEN-LAST:event_UseRHeatmapAdvance_RBActionPerformed

    private void ManualSize_RBActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ManualSize_RBActionPerformed
    {//GEN-HEADEREND:event_ManualSize_RBActionPerformed
        PlotSizeHeight_L.setEnabled(ManualSize_RB.isSelected());
        PlotSizeHeight_TB.setEnabled(ManualSize_RB.isSelected());
        PlotSizeWidth_TB.setEnabled(ManualSize_RB.isSelected());
        PlotSizeWidth_L.setEnabled(ManualSize_RB.isSelected());
    }//GEN-LAST:event_ManualSize_RBActionPerformed

    private void AutomaticSize_RBActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_AutomaticSize_RBActionPerformed
    {//GEN-HEADEREND:event_AutomaticSize_RBActionPerformed
        PlotSizeHeight_L.setEnabled(ManualSize_RB.isSelected());
        PlotSizeHeight_TB.setEnabled(ManualSize_RB.isSelected());
        PlotSizeWidth_TB.setEnabled(ManualSize_RB.isSelected());
        PlotSizeWidth_L.setEnabled(ManualSize_RB.isSelected());
    }//GEN-LAST:event_AutomaticSize_RBActionPerformed

    private void UseRHeatmapBasic_RBActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_UseRHeatmapBasic_RBActionPerformed
    {//GEN-HEADEREND:event_UseRHeatmapBasic_RBActionPerformed
        EnableDisable_BRHOptions(UseRHeatmapBasic_RB.isSelected());
        EnableDisable_ARHOptions(!UseRHeatmapBasic_RB.isSelected());
    }//GEN-LAST:event_UseRHeatmapBasic_RBActionPerformed

    private void UseIPlot_R1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_UseIPlot_R1ActionPerformed
    {//GEN-HEADEREND:event_UseIPlot_R1ActionPerformed
        EnableDisable_RHeatMapOptions(false);
    }//GEN-LAST:event_UseIPlot_R1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(HeatmapOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(HeatmapOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(HeatmapOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(HeatmapOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            @Override
            public void run()
            {
                new HeatmapOptions().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton AutomaticSize_RB;
    private javax.swing.JButton Cancel_BT;
    private javax.swing.JTextArea EpsilonDescription;
    private javax.swing.JLabel EpsilonDistance_L;
    private javax.swing.JTextField EpsilonDistance_TB;
    private javax.swing.JTabbedPane HeatmapOption_TP;
    private javax.swing.ButtonGroup HeatmapPackageOption_BG;
    private javax.swing.JLabel HeatmapTitle_L;
    private javax.swing.JTextField HeatmapTitle_TB;
    private javax.swing.JLabel HorizontalAxisTitle_L;
    private javax.swing.JTextField HorizontalAxisTitle_TB;
    private javax.swing.JRadioButton ManualSize_RB;
    private javax.swing.JButton OK_BT;
    private javax.swing.JLabel PlotSizeHeight_L;
    private javax.swing.JTextField PlotSizeHeight_TB;
    private javax.swing.JLabel PlotSizeWidth_L;
    private javax.swing.JTextField PlotSizeWidth_TB;
    private javax.swing.JLabel PlotSize_L;
    private javax.swing.JTextField RCLMarginColNames_TB;
    private javax.swing.JTextField RCLMarginRowNames_TB;
    private javax.swing.JLabel RCLMargin_L1;
    private javax.swing.JLabel RCLMargin_L2;
    private javax.swing.JEditorPane RHeatmapAdvancedOptions;
    private javax.swing.ButtonGroup RHeatmapBasicAdvanceOption;
    private javax.swing.JPanel RHeatmapBasicOptions_P;
    private javax.swing.JScrollPane RHeatmapBasicOptions_SP;
    private javax.swing.JPanel RHeatmapLabelingOptions_P;
    private javax.swing.JPanel RHeatmapOptionAdvance_P;
    private javax.swing.JPanel RHeatmapOptionBasic_P;
    private javax.swing.JTabbedPane RHeatmapOptions_T;
    private javax.swing.ButtonGroup RHeatmapSizeOptions_BG;
    private javax.swing.JPanel RHeatmap_P;
    private javax.swing.JLabel RScriptPathLabel;
    private javax.swing.JTextField RScriptPath_TB;
    private javax.swing.JLabel RowColLabeling_L;
    private javax.swing.JLabel Titles_L1;
    private javax.swing.JRadioButton UseIPlot_R1;
    private javax.swing.JRadioButton UseRHeatmapAdvance_RB;
    private javax.swing.JRadioButton UseRHeatmapBasic_RB;
    private javax.swing.JRadioButton UseRPlot_R;
    private javax.swing.JLabel VerticalAxisTitle_L;
    private javax.swing.JTextField VerticalAxisTitle_TB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

    public void SetDefaultPlotSize(Dimension dimension)
    {
        if (GlobalVariables.HeatmapOptions.autoFitRPlotSize == true)
        {
            PlotSizeHeight_TB.setText(String.valueOf(dimension.height));
            PlotSizeWidth_TB.setText(String.valueOf(dimension.width));
        }
    }

    private String GenerateRHeatmapCommand()
    {
        return "heatmap.2(space, "
               + "main = \"" + GlobalVariables.HeatmapOptions.heatmapTitle + "\", "
               + "xlab = \"" + GlobalVariables.HeatmapOptions.horizontalAxisTitle + "\", "
               + "ylab = \"" + GlobalVariables.HeatmapOptions.verticalAxisTitle + "\" ";
    }

    private void EnableDisable_RHeatMapOptions(Boolean enable)
    {
        RScriptPathLabel.setEnabled(enable);
        RScriptPath_TB.setEnabled(enable);
        RHeatmapOptions_T.setEnabled(enable);
        UseRHeatmapBasic_RB.setEnabled(enable);
        UseRHeatmapAdvance_RB.setEnabled(enable);

        if (enable == false)
        {
            EnableDisable_BRHOptions(false);
            EnableDisable_ARHOptions(false);
        }
    }

    private void EnableDisable_BRHOptions(Boolean enable)
    { // Enable/Disable Basic R Headmap options
        RHeatmapBasicOptions_SP.setEnabled(enable);
        jPanel4.setEnabled(enable);
        jPanel5.setEnabled(enable);
        RHeatmapLabelingOptions_P.setEnabled(enable);
        HeatmapTitle_L.setEnabled(enable);
        HeatmapTitle_TB.setEnabled(enable);
        HorizontalAxisTitle_L.setEnabled(enable);
        HorizontalAxisTitle_TB.setEnabled(enable);
        VerticalAxisTitle_L.setEnabled(enable);
        VerticalAxisTitle_TB.setEnabled(enable);
        Titles_L1.setEnabled(enable);
        ManualSize_RB.setEnabled(enable);
        AutomaticSize_RB.setEnabled(enable);
        PlotSize_L.setEnabled(enable);
        RowColLabeling_L.setEnabled(enable);
        RCLMargin_L1.setEnabled(enable);
        RCLMarginColNames_TB.setEnabled(enable);
        RCLMargin_L2.setEnabled(enable);
        RCLMarginRowNames_TB.setEnabled(enable);
        jPanel6.setEnabled(enable);
        jLabel1.setEnabled(enable);
        EpsilonDescription.setEnabled(enable);
        EpsilonDistance_L.setEnabled(enable);
        EpsilonDistance_TB.setEnabled(enable);
    }

    private void EnableDisable_ARHOptions(Boolean enable)
    {
        RHeatmapAdvancedOptions.setEnabled(enable);
    }
}
